make_dataset:
  seed: 17
  split_data: 0
  val_ratio: 0.15
  test_ratio: 0.10
  
# prepare:
prepare:
  benchmark: 3
  output_type: ["train", "val", "test"]
  color: "RGB" #Gray RGB
  method: ["clahe"] # clahe none
  clahe:
    clip_limit: 0.5
    tile_grid_size: [8,8] 

train:
  model_benchmark: 1
  model: "cnn" #cnn then edit in cnn.json

evaluate:
  model: "cnn"

