make_dataset:
  seed: 42
  split_data: 0
  split_ratio: 0.2

  
# prepare:
prepare:
  benchmark: 1
  train_test: 'test' #test
  resize: [224, 224]
  normalize: False
  method: "fft" #fft lbp sobel clahe
  extract_stats: false
  lbp:
    radius: 1
    n_points: 8
    method: 'default' #uniform
  sobel: 
    kernel: 3
  clahe:
    clip_limit: 2.0
    tile_grid_size: [8,8]


train:
  continue_training: False
  model_benchmark: 1
  model: "svm" 
  split_ratio: 0.2
  scaler: "standard" #standard
  svm:
    C: [1,10,100,1000,10000] #[1] #[0.1, 1, 10]
    gamma: [0.01,0.001,0.0001,0.00001] #'scale', 
    kernel: ['rbf'] #['rbf'] #['linear', 'rbf', 'poly']
  knn:
    n_neighbors: [3, 5, 7, 9, 11]
    weights: ['uniform', 'distance']
    metric: ['euclidean', 'manhattan']

# evaluate:
